name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install client dependencies
      run: cd teamcenter-client && npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Lint client
      run: cd teamcenter-client && npm run lint
    
    - name: Build
      run: npm run build
    
    - name: Test with coverage
      run: npm run test:coverage
      env:
        MOCK_MODE: 'true'
    
    - name: Merge coverage reports
      run: |
        mkdir -p ./merged-coverage
        if [ -d "./coverage" ]; then
          cp -r ./coverage/* ./merged-coverage/ || true
        fi
        if [ -d "./teamcenter-client/coverage" ]; then
          cp -r ./teamcenter-client/coverage/* ./merged-coverage/ || true
        fi
        
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./merged-coverage/
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: true
